// Dados de exemplo simulando a escola de samba "Unidos da Alegria"
// Estes dados podem ser carregados para testar o aplicativo

import type { Bloco, Integrante, Evento, Material, CategoriaMaterial } from "./types";

// Função para gerar ID único
const gerarId = () => Math.random().toString(36).substring(2, 15);

// Data atual formatada
const dataAtual = () => {
  const d = new Date();
  return `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getFullYear()}`;
};

// Data futura
const dataFutura = (dias: number) => {
  const d = new Date();
  d.setDate(d.getDate() + dias);
  return `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getFullYear()}`;
};

// ============================================
// BLOCOS DE EXEMPLO
// ============================================

export const BLOCOS_EXEMPLO: Bloco[] = [
  {
    id: gerarId(),
    nome: "Bateria",
    tipo: "segmento",
    responsavel: "Mestre João Carlos",
    descricao: "A bateria é o coração da escola, responsável pelo ritmo e energia do desfile.",
    cor: "#FF6B35",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Passistas",
    tipo: "segmento",
    responsavel: "Maria Helena",
    descricao: "Grupo de dançarinas que representam a alegria e o samba no pé.",
    cor: "#E91E63",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Mestre-Sala e Porta-Bandeira",
    tipo: "segmento",
    responsavel: "Roberto Silva",
    descricao: "Casal responsável por conduzir o pavilhão da escola com elegância.",
    cor: "#9C27B0",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Comissão de Frente",
    tipo: "segmento",
    responsavel: "Coreógrafo André Lima",
    descricao: "Grupo que abre o desfile com coreografias elaboradas.",
    cor: "#4ECDC4",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Ala das Baianas",
    tipo: "ala",
    responsavel: "Dona Conceição",
    descricao: "Ala tradicional composta por senhoras que representam a ancestralidade.",
    cor: "#FFE66D",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Ala da Comunidade",
    tipo: "ala",
    responsavel: "Carlos Eduardo",
    descricao: "Ala formada por moradores da comunidade da escola.",
    cor: "#95E1D3",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Ala das Crianças",
    tipo: "ala",
    responsavel: "Professora Ana",
    descricao: "Ala especial para as crianças da comunidade.",
    cor: "#A8D8EA",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Velha Guarda",
    tipo: "segmento",
    responsavel: "Seu Antônio",
    descricao: "Grupo de fundadores e membros históricos da escola.",
    cor: "#AA96DA",
    
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
];

// ============================================
// INTEGRANTES DE EXEMPLO
// ============================================

export const INTEGRANTES_EXEMPLO: Integrante[] = [
  // Bateria
  {
    id: gerarId(),
    nome: "João Carlos dos Santos",
    cpf: "123.456.789-00",
    rg: "12.345.678-9",
    telefone: "(21) 99999-1111",
    email: "mestrejoao@email.com",
    endereco: "Rua do Samba, 100 - Centro",
    categoria: "segmento",
    tipoSegmento: "bateria",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Mestre de Bateria",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Pedro Henrique Silva",
    cpf: "234.567.890-11",
    telefone: "(21) 99999-2222",
    email: "pedro@email.com",
    categoria: "segmento",
    tipoSegmento: "bateria",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Repique",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Lucas Oliveira",
    cpf: "345.678.901-22",
    telefone: "(21) 99999-3333",
    email: "lucas@email.com",
    categoria: "segmento",
    tipoSegmento: "bateria",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Surdo de Primeira",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Passistas
  {
    id: gerarId(),
    nome: "Maria Helena Souza",
    cpf: "456.789.012-33",
    telefone: "(21) 99999-4444",
    email: "helena@email.com",
    categoria: "segmento",
    tipoSegmento: "passistas",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Passista Principal",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Juliana Ferreira",
    cpf: "567.890.123-44",
    telefone: "(21) 99999-5555",
    email: "juliana@email.com",
    categoria: "segmento",
    tipoSegmento: "passistas",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Passista",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Mestre-Sala e Porta-Bandeira
  {
    id: gerarId(),
    nome: "Roberto Silva Neto",
    cpf: "678.901.234-55",
    telefone: "(21) 99999-6666",
    email: "roberto@email.com",
    categoria: "segmento",
    tipoSegmento: "mestre_sala_porta_bandeira",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Mestre-Sala Primeiro Casal",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Fernanda Costa Lima",
    cpf: "789.012.345-66",
    telefone: "(21) 99999-7777",
    email: "fernanda@email.com",
    categoria: "segmento",
    tipoSegmento: "mestre_sala_porta_bandeira",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Porta-Bandeira Primeiro Casal",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Ala das Baianas
  {
    id: gerarId(),
    nome: "Conceição Maria da Silva",
    cpf: "890.123.456-77",
    telefone: "(21) 99999-8888",
    email: "conceicao@email.com",
    categoria: "desfilante",
    tipoDesfilante: "ala_comunidade",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    observacoes: "Coordenadora - Ala das Baianas",
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Diretoria
  {
    id: gerarId(),
    nome: "Antônio Carlos Pereira",
    cpf: "901.234.567-88",
    telefone: "(21) 99999-9999",
    email: "presidente@unidosdaalegria.com.br",
    categoria: "diretoria",
    cargoDiretoria: "presidente",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Márcia Regina Santos",
    cpf: "012.345.678-99",
    telefone: "(21) 99998-0000",
    email: "financeiro@unidosdaalegria.com.br",
    categoria: "diretoria",
    cargoDiretoria: "coordenador",
    blocosIds: [],
    qrCodeId: `QR_${gerarId()}`,
    ativo: true,
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
];

// ============================================
// EVENTOS DE EXEMPLO
// ============================================

export const EVENTOS_EXEMPLO: Evento[] = [
  {
    id: gerarId(),
    titulo: "Ensaio Técnico da Bateria",
    tipo: "ensaio",
    data: dataFutura(3),
    horario: "20:00",
    local: "Quadra da Escola - Rua do Samba, 500",
    descricao: "Ensaio técnico semanal da bateria. Obrigatório para todos os ritmistas.",
    status: "agendado",
    checkInAberto: false,
    blocosIds: [],
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    titulo: "Ensaio Geral de Quadra",
    tipo: "ensaio",
    data: dataFutura(7),
    horario: "21:00",
    local: "Quadra da Escola - Rua do Samba, 500",
    descricao: "Ensaio geral com todos os segmentos. Presença obrigatória.",
    status: "agendado",
    checkInAberto: false,
    blocosIds: [],
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    titulo: "Feijoada Beneficente",
    tipo: "feijoada",
    data: dataFutura(14),
    horario: "12:00",
    local: "Quadra da Escola - Rua do Samba, 500",
    descricao: "Feijoada beneficente para arrecadação de fundos. Aberta ao público.",
    status: "agendado",
    checkInAberto: false,
    blocosIds: [],
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    titulo: "Reunião de Diretoria",
    tipo: "reuniao",
    data: dataFutura(2),
    horario: "19:00",
    local: "Sala de Reuniões - Sede Administrativa",
    descricao: "Reunião mensal da diretoria para planejamento do carnaval.",
    status: "agendado",
    checkInAberto: false,
    blocosIds: [],
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    titulo: "Ensaio de Rua",
    tipo: "ensaio",
    data: dataFutura(21),
    horario: "22:00",
    local: "Avenida Principal - Centro",
    descricao: "Ensaio de rua com simulação do desfile. Todas as alas participam.",
    status: "agendado",
    checkInAberto: false,
    blocosIds: [],
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
];

// ============================================
// MATERIAIS DE EXEMPLO
// ============================================

export const MATERIAIS_EXEMPLO: Material[] = [
  // Instrumentos
  {
    id: gerarId(),
    nome: "Surdo de Primeira",
    categoria: "instrumentos" as CategoriaMaterial,
    descricao: "Surdo grande para marcação principal da bateria",
    quantidadeDisponivel: 20,
    quantidadeEmUso: 18,
    quantidadeNecessaria: 25,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Surdo de Segunda",
    categoria: "instrumentos" as CategoriaMaterial,
    descricao: "Surdo médio para resposta",
    quantidadeDisponivel: 15,
    quantidadeEmUso: 15,
    quantidadeNecessaria: 20,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Repique",
    categoria: "instrumentos" as CategoriaMaterial,
    descricao: "Tambor agudo para repiques e chamadas",
    quantidadeDisponivel: 25,
    quantidadeEmUso: 22,
    quantidadeNecessaria: 30,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Tamborim",
    categoria: "instrumentos" as CategoriaMaterial,
    descricao: "Tamborim com baqueta de nylon",
    quantidadeDisponivel: 50,
    quantidadeEmUso: 45,
    quantidadeNecessaria: 60,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Caixa de Guerra",
    categoria: "instrumentos" as CategoriaMaterial,
    descricao: "Caixa para marcação rítmica",
    quantidadeDisponivel: 30,
    quantidadeEmUso: 28,
    quantidadeNecessaria: 35,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Fantasias
  {
    id: gerarId(),
    nome: "Fantasia Passista - Modelo 2025",
    categoria: "fantasia" as CategoriaMaterial,
    descricao: "Fantasia completa para passistas com plumas e pedrarias",
    quantidadeDisponivel: 30,
    quantidadeEmUso: 24,
    quantidadeNecessaria: 30,
    tamanho: "M",
    localizacao: "Ateliê - Setor Fantasias",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Fantasia Baiana - Saia Rodada",
    categoria: "fantasia" as CategoriaMaterial,
    descricao: "Saia rodada tradicional para ala das baianas",
    quantidadeDisponivel: 100,
    quantidadeEmUso: 80,
    quantidadeNecessaria: 100,
    tamanho: "G",
    localizacao: "Ateliê - Setor Fantasias",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Chapéu de Baiana",
    categoria: "aderecos" as CategoriaMaterial,
    descricao: "Chapéu tradicional com frutas decorativas",
    quantidadeDisponivel: 100,
    quantidadeEmUso: 80,
    quantidadeNecessaria: 100,
    localizacao: "Ateliê - Setor Adereços",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Roupa Porta-Bandeira",
    categoria: "fantasia" as CategoriaMaterial,
    descricao: "Vestido luxuoso para porta-bandeira primeiro casal",
    quantidadeDisponivel: 2,
    quantidadeEmUso: 2,
    quantidadeNecessaria: 2,
    tamanho: "P",
    localizacao: "Ateliê - Setor VIP",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Roupa Mestre-Sala",
    categoria: "fantasia" as CategoriaMaterial,
    descricao: "Traje completo para mestre-sala primeiro casal",
    quantidadeDisponivel: 2,
    quantidadeEmUso: 2,
    quantidadeNecessaria: 2,
    tamanho: "M",
    localizacao: "Ateliê - Setor VIP",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  // Materiais diversos
  {
    id: gerarId(),
    nome: "Pele de Surdo",
    categoria: "ferramentas" as CategoriaMaterial,
    descricao: "Pele de reposição para surdos",
    quantidadeDisponivel: 50,
    quantidadeEmUso: 0,
    quantidadeNecessaria: 100,
    localizacao: "Almoxarifado - Setor Manutenção",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Baqueta de Repique",
    categoria: "ferramentas" as CategoriaMaterial,
    descricao: "Baqueta de nylon para repique",
    quantidadeDisponivel: 100,
    quantidadeEmUso: 50,
    quantidadeNecessaria: 150,
    localizacao: "Almoxarifado - Setor Instrumentos",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Plumas Coloridas (pacote)",
    categoria: "tecidos" as CategoriaMaterial,
    descricao: "Pacote com 100 plumas para confecção de fantasias",
    quantidadeDisponivel: 200,
    quantidadeEmUso: 150,
    quantidadeNecessaria: 300,
    localizacao: "Ateliê - Setor Materiais",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
  {
    id: gerarId(),
    nome: "Pedrarias (pacote 1000un)",
    categoria: "tecidos" as CategoriaMaterial,
    descricao: "Pacote com 1000 pedrarias para bordado",
    quantidadeDisponivel: 50,
    quantidadeEmUso: 30,
    quantidadeNecessaria: 80,
    localizacao: "Ateliê - Setor Materiais",
    criadoEm: dataAtual(),
    atualizadoEm: dataAtual(),
  },
];

// ============================================
// CONFIGURAÇÃO DA ESCOLA DE EXEMPLO
// ============================================

export const ESCOLA_EXEMPLO = {
  nome: "Unidos da Alegria",
  nomeCompleto: "G.R.E.S. Unidos da Alegria",
  corPrimaria: "#FF6B35",
  corSecundaria: "#4ECDC4",
  cidade: "Rio de Janeiro",
  bairro: "Centro",
  telefone: "(21) 3333-4444",
  email: "contato@unidosdaalegria.com.br",
  instagram: "@unidosdaalegria",
};
